dist: trusty
group: deprecated-2017Q4
language: python
python:
  - "2.7"
services:
  - postgresql
addons:
  postgresql: "9.3"
install: ./bin/travis-install-dependencies
script: ./bin/travis-run-tests
after_success:
  - coveralls
